// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpQnu2E_ZbdU4gQl9h0XNm-Irr_FwU_c',
    appId: '1:357017766948:web:068435292923001c025cb1',
    messagingSenderId: '357017766948',
    projectId: 'pegasus-mvp-70271',
    authDomain: 'pegasus-mvp-70271.firebaseapp.com',
    storageBucket: 'pegasus-mvp-70271.firebasestorage.app',
    measurementId: 'G-QYLN5W1VNY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiifa_vLRpamAkEgCi8oArqiwSX4pkyoc',
    appId: '1:357017766948:android:a02e7976039067d7025cb1',
    messagingSenderId: '357017766948',
    projectId: 'pegasus-mvp-70271',
    storageBucket: 'pegasus-mvp-70271.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP127cp_yJJJtOn-42ilytKz9aoZ3zP6k',
    appId: '1:357017766948:ios:60cd5d07a24347e0025cb1',
    messagingSenderId: '357017766948',
    projectId: 'pegasus-mvp-70271',
    storageBucket: 'pegasus-mvp-70271.firebasestorage.app',
    iosBundleId: 'com.example.proyectoStartupsTitulo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP127cp_yJJJtOn-42ilytKz9aoZ3zP6k',
    appId: '1:357017766948:ios:60cd5d07a24347e0025cb1',
    messagingSenderId: '357017766948',
    projectId: 'pegasus-mvp-70271',
    storageBucket: 'pegasus-mvp-70271.firebasestorage.app',
    iosBundleId: 'com.example.proyectoStartupsTitulo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZpQnu2E_ZbdU4gQl9h0XNm-Irr_FwU_c',
    appId: '1:357017766948:web:9e9be64b14585467025cb1',
    messagingSenderId: '357017766948',
    projectId: 'pegasus-mvp-70271',
    authDomain: 'pegasus-mvp-70271.firebaseapp.com',
    storageBucket: 'pegasus-mvp-70271.firebasestorage.app',
    measurementId: 'G-VT8XTDLJZG',
  );
}
