// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJK2a6ETHzHAKyiYqMDb6ipvTthylqjSc',
    appId: '1:600449930391:web:33ac543661582ad96a45d2',
    messagingSenderId: '600449930391',
    projectId: 'pegasus73-14cf4',
    authDomain: 'pegasus73-14cf4.firebaseapp.com',
    storageBucket: 'pegasus73-14cf4.firebasestorage.app',
    measurementId: 'G-N61HT2QBCK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1qBA38VnjrfsQl-fGNaVvmxm0qr2N4c',
    appId: '1:600449930391:android:e0185748f62e657c6a45d2',
    messagingSenderId: '600449930391',
    projectId: 'pegasus73-14cf4',
    storageBucket: 'pegasus73-14cf4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtKy7w2A-BTM-T1Omh33tjr-HnBlHmxOk',
    appId: '1:600449930391:ios:6e40eee343a367da6a45d2',
    messagingSenderId: '600449930391',
    projectId: 'pegasus73-14cf4',
    storageBucket: 'pegasus73-14cf4.firebasestorage.app',
    iosBundleId: 'com.example.proyectoStartupsTitulo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtKy7w2A-BTM-T1Omh33tjr-HnBlHmxOk',
    appId: '1:600449930391:ios:6e40eee343a367da6a45d2',
    messagingSenderId: '600449930391',
    projectId: 'pegasus73-14cf4',
    storageBucket: 'pegasus73-14cf4.firebasestorage.app',
    iosBundleId: 'com.example.proyectoStartupsTitulo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJK2a6ETHzHAKyiYqMDb6ipvTthylqjSc',
    appId: '1:600449930391:web:4fd565ab9d70d35d6a45d2',
    messagingSenderId: '600449930391',
    projectId: 'pegasus73-14cf4',
    authDomain: 'pegasus73-14cf4.firebaseapp.com',
    storageBucket: 'pegasus73-14cf4.firebasestorage.app',
    measurementId: 'G-HGPVGG3Y8V',
  );
}
